//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemLog
    {
        public long ID { get; set; }
        public string ModulePage { get; set; }
        public string Remark { get; set; }
        public System.DateTime CreationDate { get; set; }
        public Nullable<int> CreationUserID { get; set; }
    
        public virtual SystemUser SystemUser { get; set; }
    }
}
