//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApp.EFModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long ID { get; set; }
        public string UserName { get; set; }
        public string DisplayName { get; set; }
        public string Password { get; set; }
        public string Country { get; set; }
        public string Province { get; set; }
        public string City { get; set; }
        public string Sex { get; set; }
        public string Email { get; set; }
        public string Phone { get; set; }
        public string OpenID { get; set; }
        public string UserFace { get; set; }
        public System.DateTime CreationDateTime { get; set; }
        public Nullable<System.DateTime> AttentionDateTime { get; set; }
        public Nullable<System.DateTime> CancelAttentionDateTime { get; set; }
        public bool CanAttention { get; set; }
        public string Remark { get; set; }
        public Nullable<int> SourceProductID { get; set; }
        public bool IsUse { get; set; }
    }
}
